project_id = "ugzhiztkzeyhpybnsgnj"

[functions.awin-sync]
verify_jwt = false

[functions.fetch-feed]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.google-merchant-feed]
verify_jwt = false

[functions.validate-images]
verify_jwt = false
